name: Rebuild Container P

on:
  repository_dispatch:
    types: [trigger-rebuild]

jobs:
  handle_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Receive tag
        run: |
          echo "Received new_tag=${{ github.event.client_payload.new_tag }}"
          echo "Received old_tag=${{ github.event.client_payload.old_tag }}"
